import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/structure/Header";
import Promotion from "@/components/structure/Promotion";
import Footer from "@/components/structure/Footer";
import Section from "@/components/shared/Section";
import CardList from "@/components/shared/CardList";
import Video from "@/components/shared/Video";
import ContactForm from "@/components/shared/ContactForm";
import ContactInfo from "@/components/shared/ContactInfo";
import SkillChart from "@/components/shared/SkillChart";

const inter = Inter({ subsets: ["latin"] });

const DATA = {
  skills: [
    {
      id: "u1",
      title: "React.js",
      percentage: 100,
    },
    {
      id: "u2",
      title: "Next.js",
      percentage: 90,
    },
    {
      id: "u3",
      title: "Vue.js",
      percentage: 30,
    },
    {
      id: "u4",
      title: "HTML",
      percentage: 80,
    },
    {
      id: "u5",
      title: "CSS",
      percentage: 70,
    },
    {
      id: "u6",
      title: "Sass",
      percentage: 80,
    },
    {
      id: "u7",
      title: "Typescript",
      percentage: 70,
    },
  ],
  code: [
    {
      id: "u1",
      title: "GitHub",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "https://github.com/matheusximenes",
      img: {
        description: "",
        src: "./code/github.svg",
        width: 160,
        height: 160,
      },
    },
    {
      id: "u2",
      title: "CodesandBox",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "https://codesandbox.io/u/Ximenes",
      img: {
        description: "",
        src: "./code/codesandbox.svg",
        width: 160,
        height: 160,
      },
    },
  ],
  uxui: [
    {
      id: "u1",
      title: "GitHub",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "",
      img: {
        description: "",
        src: "./code/codesandbox.svg",
        width: 160,
        height: 160,
      },
    },
    {
      id: "u2",
      title: "CodesandBox",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "",
      img: {
        description: "",
        src: "./code/codesandbox.svg",
        width: 160,
        height: 160,
      },
    },
  ],
  projects: [
    {
      id: "u1",
      title: "Project 1",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "",
      img: {
        description: "",
        src: "./code/codesandbox.svg",
        width: 160,
        height: 160,
      },
    },
    {
      id: "u2",
      title: "project 2",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "",
      img: {
        description: "",
        src: "./code/codesandbox.svg",
        width: 160,
        height: 160,
      },
    },
    {
      id: "u4",
      title: "project 3",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "",
      img: {
        description: "",
        src: "./code/codesandbox.svg",
        width: 160,
        height: 160,
      },
    },
  ],
};

export default function Home() {
  return (
    <>
      <Head>
        <title>MatheusXimenes - Portfolio 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <aside className="main__aside">
          {/* <div className="aside__image">
            <video autoPlay loop style={{ width: "1600px", height: "1200px" }}>
              <source src="/video.mov" />
            </video>
          </div> */}
          <Header />
          <Promotion />
          <Footer />
        </aside>
        <div className="main__content">
          <Section
            id="about"
            title="About"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
              sint ad omnis!"
          >
            <Video />
            <div className="about__subsection">
              <h3>How is Matheus Ximenes?</h3>
              <p>
                Hey! I am Matheus Ximenes a proud Brazilian, Canada resident,
                and parent of two lovely girls. My heart is constantly divided
                between Engineering (Profession) and Graphic Design (Side
                Projects). On one side is my love for coding applications,
                planning/developing websites, and producing coding solutions
                like POCs. On the other hand, my passion for hand drawing,
                graphic design and photography.
              </p>
              <p>
                On my Front End Engineer skill set, I primarily work with
                Semantic HTML (SEO), CSS3 / SASS, modern Javascript / ES6+ /
                Typescript / ReactJS / VueJS applying Unit testing using Jest,
                E2e testing using Cypress, Storybook for Design System and A11y
                (Accessibility - Screen Readers and Accessible Navigation).
                Nowadays, I mainly focus on developing my knowledge as Full
                Stack Engineer MERN/MEVN Stack (MongoDB, Express, ReactJS/VueJS,
                and NodeJS). Some years ago, I had work experience as Back End
                Developer with PHP, Java, PostgreSQL, MySQL, and Windows Server.
              </p>
              <SkillChart list={DATA.skills} />
              <p>Redbubble Store: </p>
            </div>
          </Section>
          <Section
            id="code"
            title="Code"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
              sint ad omnis!"
          >
            <CardList list={DATA.code} />
          </Section>
          <Section
            id="ux&ui"
            title="UX/UI"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
              sint ad omnis!"
          >
            <CardList list={DATA.uxui} />
          </Section>
          <Section
            id="projects"
            title="Projects"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
              sint ad omnis!"
          >
            <CardList list={DATA.projects} />
          </Section>
          <Section
            id="contact"
            title="Contact"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
              sint ad omnis!"
          >
            <p>We can do so much together. Lets chat.</p>
            <ContactInfo />
            <ContactForm />
          </Section>
        </div>
      </main>
    </>
  );
}
