import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/structure/Header";
import Promotion from "@/components/structure/Promotion";
import Footer from "@/components/structure/Footer";
import Section from "@/components/shared/Section";
import Card from "@/components/shared/Card";
import CardList from "@/components/shared/CardList";

const inter = Inter({ subsets: ["latin"] });

const DATA = {
  skills: [
    {
      id: "u1",
      title: "React.js",
      percentage: 80,
    },
  ],
  code: [
    {
      id: "u1",
      title: "GitHub",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "",
      img: {
        description: "",
        src: "./github.svg",
        width: 160,
        height: 160,
      },
    },
    {
      id: "u2",
      title: "CodesandBox",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "",
      img: {
        description: "",
        src: "./codesandbox.svg",
        width: 160,
        height: 160,
      },
    },
  ],
  uxui: [
    {
      id: "u1",
      title: "GitHub",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "",
      img: {
        description: "",
        src: "./codesandbox.svg",
        width: 160,
        height: 160,
      },
    },
    {
      id: "u2",
      title: "CodesandBox",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "",
      img: {
        description: "",
        src: "./codesandbox.svg",
        width: 160,
        height: 160,
      },
    },
  ],
  projects: [
    {
      id: "u1",
      title: "Project 1",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "",
      img: {
        description: "",
        src: "./codesandbox.svg",
        width: 160,
        height: 160,
      },
    },
    {
      id: "u2",
      title: "project 2",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "",
      img: {
        description: "",
        src: "./codesandbox.svg",
        width: 160,
        height: 160,
      },
    },
    {
      id: "u4",
      title: "project 3",
      description: "Lorem ipsum dolor sit amet consectetur.",
      linkUrl: "",
      img: {
        description: "",
        src: "./codesandbox.svg",
        width: 160,
        height: 160,
      },
    },
  ],
};

export default function Home() {
  return (
    <>
      <Head>
        <title>MatheusXimenes - Portfolio 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <aside className="main__aside">
          {/* <div className="aside__image">
            <video autoPlay loop style={{ width: "1600px", height: "1200px" }}>
              <source src="/video.mov" />
            </video>
          </div> */}
          <Header />
          <Promotion />
          <Footer />
        </aside>
        <div className="main__content">
          <Section
            id="about"
            title="About"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
              sint ad omnis!"
          >
            <div className="about__subsection">
              <iframe
                width="640"
                height="390"
                src="https://www.youtube.com/embed/tgbNymZ7vqY"
              ></iframe>
            </div>

            <div className="about__subsection">
              <h3>How is Matheus Ximenes?</h3>
              <p>
                Hey! I'm Matheus Ximenes a proud Brazilian, Canada resident, and
                parent of two lovely girls. My heart is constantly divided
                between Engineering (Profession) and Graphic Design (Side
                Projects). On one side is my love for coding applications,
                planning/developing websites, and producing coding solutions
                like POCs. On the other hand, my passion for hand drawing,
                graphic design and photography.
              </p>
              <p>
                On my Front End Engineer skill set, I primarily work with
                Semantic HTML (SEO), CSS3 / SASS, modern Javascript / ES6+ /
                Typescript / ReactJS / VueJS applying Unit testing using Jest,
                E2e testing using Cypress, Storybook for Design System and A11y
                (Accessibility - Screen Readers and Accessible Navigation).
                Nowadays, I mainly focus on developing my knowledge as Full
                Stack Engineer MERN/MEVN Stack (MongoDB, Express, ReactJS/VueJS,
                and NodeJS). Some years ago, I had work experience as Back End
                Developer with PHP, Java, PostgreSQL, MySQL, and Windows Server.
              </p>
            </div>
            <div className="about__skill-chart">Skills Chart</div>
          </Section>
          <Section
            id="code"
            title="Code"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
              sint ad omnis!"
          >
            <CardList list={DATA.code} />
          </Section>
          <Section
            id="ux&ui"
            title="UX/UI"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
              sint ad omnis!"
          >
            <CardList list={DATA.uxui} />
          </Section>
          <Section
            id="projects&ui"
            title="Projects"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
              sint ad omnis!"
          >
            <CardList list={DATA.projects} />
          </Section>
          <Section
            id="contact"
            title="Contact"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
              sint ad omnis!"
          >
            <p>We can do so much together. Let’s chat.</p>
            <ul className="contact__list">
              <li>
                If you wanna email me:{" "}
                <span className="list__bold">mattximca@gmail.com</span>
              </li>
              <li>
                If you wanna to hear my voice:{" "}
                <span className="list__bold">+ 1 226 977 0251</span>
              </li>
              <li>
                If you wanna to be influenced:{" "}
                <span className="list__bold">@matheusximenes</span>
              </li>
              <li>
                If you wanna to see me:{" "}
                <span className="list__bold">
                  I' ll be at Huron Lake eating sandwich over the sun.
                </span>
              </li>
            </ul>
            <form className="contact__form">
              <div className="form__row">
                <div className="form__column">
                  <label htmlFor="">Name</label>
                  <input type="text" placeholder="Name" />
                </div>
                <div className="form__column">
                  <label htmlFor="">Phone</label>
                  <input type="text" placeholder="Phone" />
                </div>
              </div>
              <div className="form__row">
                <div className="form__column">
                  <label htmlFor="">Subject</label>
                  <input type="text" placeholder="Subject" />
                </div>
                <div className="form__column">
                  <label htmlFor="">Email</label>
                  <input type="text" placeholder="Email" />
                </div>
              </div>
              <div className="form__row">
                <div className="form__column">
                  <label htmlFor="">Message</label>
                  <textarea rows={4} placeholder="Message" />
                </div>
              </div>
              <button className="form__button" type="submit">
                Message
              </button>
            </form>
          </Section>
        </div>
      </main>
    </>
  );
}
